import { createRequire } from "module";
const require = createRequire(import.meta.url);
// exceljs + jszip are CommonJS — require() gives reliable interop under Turbopack
const ExcelJS = require("exceljs") as any;
const JSZip = require("jszip") as any;
import { COMPLIANCE_FRAMEWORKS, EXECUTION_METHODOLOGY, getTenderType } from "./constants";
import type { GeneratedProposal, TenderProject, BrandProfile } from "@prisma/client";

// ─── PDF generation (printable HTML that browsers render to PDF) ─────────────
// We generate a print-optimized HTML document instead of a binary PDF to avoid
// native font/binary bundling issues in the serverless runtime. The HTML opens
// with a "Save as PDF" prompt and is fully branded.

export function generateProposalPDF(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null
): Promise<Buffer> {
  const primary = brand?.primaryColor ?? "#1E3A8A";
  const accent = brand?.accentColor ?? "#0EA5E9";
  const tenderType = getTenderType(project.category);

  // Convert markdown to simple HTML
  const mdToHtml = (md: string) =>
    md
      .replace(/^### (.*)$/gm, '<h3 style="color:' + primary + ';margin:18px 0 8px">$1</h3>')
      .replace(/^## (.*)$/gm, '<h2 style="color:' + primary + ';margin:24px 0 10px;border-bottom:2px solid ' + accent + ';padding-bottom:4px">$1</h2>')
      .replace(/^# (.*)$/gm, '<h1 style="color:' + primary + ';margin:28px 0 12px">$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/^- (.*)$/gm, "<li>$1</li>")
      .replace(/\|(.+)\|/g, (m) => "<tr>" + m.split("|").filter(Boolean).map((c) => `<td style="border:1px solid #e2e8f0;padding:6px 10px;font-size:11px">${c.trim()}</td>`).join("") + "</tr>")
      .replace(/(<tr>[\s\S]+?<\/tr>)/g, '<table style="border-collapse:collapse;width:100%;margin:10px 0">$1</table>')
      .replace(/---/g, '<hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0" />');

  const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>${project.title} — Technical & Financial Proposal</title>
<style>
  @page { size: A4; margin: 20mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', 'IBM Plex Sans Arabic', Arial, sans-serif; color: #0f172a; margin: 0; line-height: 1.6; font-size: 12px; }
  .cover { background: linear-gradient(135deg, ${primary}, ${accent}); color: white; padding: 60px 40px; border-radius: 12px; margin-bottom: 30px; }
  .cover h1 { font-size: 32px; margin: 0 0 8px; color: white; }
  .cover .subtitle { font-size: 18px; opacity: 0.9; }
  .cover .ref { font-size: 13px; opacity: 0.8; margin-top: 16px; font-family: monospace; }
  .meta { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 24px; }
  .meta div { display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px dashed #e2e8f0; }
  .meta div:last-child { border: none; }
  .meta .label { font-weight: 600; color: ${primary}; }
  h1, h2, h3 { page-break-after: avoid; }
  ul, ol { padding-left: 20px; }
  li { margin: 4px 0; }
  .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 6px; }
  @media print { .no-print { display: none; } }
  .print-btn { position: fixed; top: 16px; right: 16px; background: ${primary}; color: white; border: none; padding: 10px 18px; border-radius: 8px; cursor: pointer; font-size: 13px; box-shadow: 0 4px 12px rgba(0,0,0,.15); }
</style></head>
<body>
  <button class="print-btn no-print" onclick="window.print()">🖨 Save as PDF</button>
  <div class="cover">
    <h1>${brand?.tagline ?? "Arabclue"}</h1>
    <div class="subtitle">Technical & Financial Proposal</div>
    <div class="ref">Etimad Ref: ${project.etimadRef ?? "N/A"} · ${tenderType.name} / ${tenderType.nameAr}</div>
  </div>
  <div class="meta">
    <div><span class="label">Project Title</span><span>${project.title}</span></div>
    <div><span class="label">Tender Type</span><span>${tenderType.name}</span></div>
    <div><span class="label">Budget</span><span>${project.currency} ${(project.budget ?? 0).toLocaleString()}</span></div>
    <div><span class="label">Evaluation</span><span>Technical ${tenderType.evaluationSplit.technical}% / Financial ${tenderType.evaluationSplit.financial}%</span></div>
    <div><span class="label">SLA Penalty</span><span>${tenderType.slaPerWeek}%/week (max ${tenderType.slaMaxPenalty}%)</span></div>
    <div><span class="label">Generated</span><span>${new Date().toISOString()}</span></div>
  </div>
  ${mdToHtml(proposal.contentMd ?? "")}
  <div class="footer">Generated by Arabclue · PDPL Compliant · KSA Data Residency · Vision 2030 Aligned</div>
</body></html>`;

  return Promise.resolve(Buffer.from(html, "utf8"));
}

// ─── XLSX generation (Compliance Matrix & BoQ) ───────────────────────────────

export async function generateComplianceMatrixXLSX(
  project: TenderProject,
  brand: BrandProfile | null
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Arabclue";
  wb.created = new Date();

  const ws = wb.addWorksheet("Compliance Matrix", {
    views: [{ rightToLeft: false }],
    properties: { defaultRowHeight: 20 },
  });

  // Title row
  ws.mergeCells("A1:F1");
  const titleCell = ws.getCell("A1");
  titleCell.value = `Arabclue Compliance Matrix — ${project.title}`;
  titleCell.font = { size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E3A8A" } };
  titleCell.alignment = { vertical: "middle", horizontal: "center" };
  ws.getRow(1).height = 30;

  // Header
  const headers = ["Framework", "Control ID", "Title", "Requirement", "Level", "Status"];
  headers.forEach((h, i) => {
    const cell = ws.getCell(2, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };
    cell.alignment = { vertical: "middle", horizontal: "center" };
    cell.border = { bottom: { style: "medium", color: { argb: "FF0EA5E9" } } };
  });
  ws.getRow(2).height = 22;

  const tenderType = getTenderType(project.category);
  let row = 3;
  for (const fw of COMPLIANCE_FRAMEWORKS.filter((f) => tenderType.complianceScope.includes(f.id))) {
    for (const ctrl of fw.controls) {
      ws.getCell(row, 1).value = fw.id;
      ws.getCell(row, 2).value = ctrl.controlId;
      ws.getCell(row, 3).value = ctrl.title;
      ws.getCell(row, 4).value = ctrl.requirement;
      ws.getCell(row, 5).value = ctrl.level;
      ws.getCell(row, 6).value = "COMPLIANT";
      ws.getCell(row, 6).font = { bold: true, color: { argb: "FF059669" } };
      ws.getRow(row).height = 28;
      // zebra
      if (row % 2 === 0) {
        for (let c = 1; c <= 6; c++) {
          ws.getCell(row, c).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F5F9" } };
        }
      }
      ws.getCell(row, 1).alignment = { vertical: "middle" };
      ws.getCell(row, 4).alignment = { wrapText: true, vertical: "middle" };
      row++;
    }
  }

  // Column widths
  ws.columns = [
    { width: 16 },
    { width: 14 },
    { width: 32 },
    { width: 55 },
    { width: 10 },
    { width: 14 },
  ];

  // Freeze header
  ws.views = [{ state: "frozen", ySplit: 2 }];

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}

export async function generateBoQXLSX(
  project: TenderProject,
  brand: BrandProfile | null
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Arabclue";
  wb.created = new Date();
  const ws = wb.addWorksheet("Financial BoQ");

  // Title
  ws.mergeCells("A1:G1");
  const tc = ws.getCell("A1");
  tc.value = `Financial Bill of Quantities — ${project.title}`;
  tc.font = { size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  tc.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E3A8A" } };
  tc.alignment = { vertical: "middle", horizontal: "center" };
  ws.getRow(1).height = 30;

  const headers = ["Item #", "Description", "Unit", "Qty", "Unit Price (SAR)", "Total (SAR)", "Local Content %"];
  headers.forEach((h, i) => {
    const cell = ws.getCell(2, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };
    cell.alignment = { vertical: "middle", horizontal: "center" };
  });
  ws.getRow(2).height = 22;

  const tenderType = getTenderType(project.category);
  const items = generateBoQItems(tenderType.id, project.budget ?? tenderType.typicalBudget);
  let row = 3;
  let subtotal = 0;
  items.forEach((item, idx) => {
    const total = item.qty * item.unitPrice;
    subtotal += total;
    ws.getCell(row, 1).value = idx + 1;
    ws.getCell(row, 2).value = item.description;
    ws.getCell(row, 3).value = item.unit;
    ws.getCell(row, 4).value = item.qty;
    ws.getCell(row, 5).value = item.unitPrice;
    ws.getCell(row, 6).value = total;
    ws.getCell(row, 7).value = item.localContentPct;
    ws.getCell(row, 5).numFmt = "#,##0.00";
    ws.getCell(row, 6).numFmt = "#,##0.00";
    ws.getCell(row, 7).numFmt = "0%";
    if (row % 2 === 0) {
      for (let c = 1; c <= 7; c++) {
        ws.getCell(row, c).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F5F9" } };
      }
    }
    row++;
  });

  // Subtotal, VAT, Local Content preference
  const vat = subtotal * 0.15;
  const localContentPref = subtotal * 0.10;
  const grandTotal = subtotal + vat - localContentPref;

  ws.getCell(row, 5).value = "Subtotal";
  ws.getCell(row, 6).value = subtotal;
  ws.getCell(row + 1, 5).value = "VAT (15%)";
  ws.getCell(row + 1, 6).value = vat;
  ws.getCell(row + 2, 5).value = "Local Content Preference (-10%)";
  ws.getCell(row + 2, 6).value = -localContentPref;
  ws.getCell(row + 3, 5).value = "GRAND TOTAL";
  ws.getCell(row + 3, 6).value = grandTotal;
  for (let r = row; r <= row + 3; r++) {
    ws.getCell(r, 5).font = { bold: true };
    ws.getCell(r, 6).font = { bold: true };
    ws.getCell(r, 6).numFmt = "#,##0.00";
  }
  ws.getCell(row + 3, 5).font = { bold: true, color: { argb: "FF1E3A8A" }, size: 12 };
  ws.getCell(row + 3, 6).font = { bold: true, color: { argb: "FF1E3A8A" }, size: 12 };

  ws.columns = [
    { width: 8 }, { width: 45 }, { width: 10 }, { width: 8 },
    { width: 22 }, { width: 18 }, { width: 16 },
  ];
  ws.views = [{ state: "frozen", ySplit: 2 }];

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}

function generateBoQItems(tenderType: string, budget: number) {
  const base = budget > 0 ? budget : 1000000;
  if (tenderType === "IT") {
    return [
      { description: "Solution Architecture & Design", unit: "LS", qty: 1, unitPrice: base * 0.08, localContentPct: 0.6 },
      { description: "Platform Development (Sprint 1-8)", unit: "Sprint", qty: 8, unitPrice: base * 0.06, localContentPct: 0.7 },
      { description: "Cloud Infrastructure (STC Cloud, 12mo)", unit: "Month", qty: 12, unitPrice: base * 0.01, localContentPct: 1.0 },
      { description: "Security Hardening (NCA ECC-1)", unit: "LS", qty: 1, unitPrice: base * 0.05, localContentPct: 0.8 },
      { description: "Integration & API Gateway", unit: "LS", qty: 1, unitPrice: base * 0.07, localContentPct: 0.65 },
      { description: "Training & Knowledge Transfer", unit: "Session", qty: 20, unitPrice: base * 0.002, localContentPct: 1.0 },
      { description: "O&M Support (Tier 2/3, 12mo)", unit: "Month", qty: 12, unitPrice: base * 0.015, localContentPct: 0.9 },
    ];
  }
  if (tenderType === "CONSTRUCTION") {
    return [
      { description: "Site Mobilization & Setup", unit: "LS", qty: 1, unitPrice: base * 0.05, localContentPct: 0.9 },
      { description: "Excavation & Earthworks", unit: "m³", qty: 5000, unitPrice: base * 0.00002, localContentPct: 0.95 },
      { description: "Concrete Works (Structure)", unit: "m³", qty: 2000, unitPrice: base * 0.00008, localContentPct: 0.85 },
      { description: "Steel Reinforcement", unit: "Ton", qty: 300, unitPrice: base * 0.0008, localContentPct: 0.7 },
      { description: "MEP Installation", unit: "LS", qty: 1, unitPrice: base * 0.25, localContentPct: 0.6 },
      { description: "Finishes & Cladding", unit: "LS", qty: 1, unitPrice: base * 0.2, localContentPct: 0.75 },
      { description: "Testing & Commissioning", unit: "LS", qty: 1, unitPrice: base * 0.07, localContentPct: 0.8 },
    ];
  }
  // Generic / consulting / operations / medical
  return [
    { description: "Project Management & Governance", unit: "Month", qty: 12, unitPrice: base * 0.04, localContentPct: 0.9 },
    { description: "Core Service Delivery", unit: "LS", qty: 1, unitPrice: base * 0.45, localContentPct: 0.7 },
    { description: "Quality Assurance & Compliance", unit: "LS", qty: 1, unitPrice: base * 0.1, localContentPct: 0.85 },
    { description: "Reporting & Analytics", unit: "Month", qty: 12, unitPrice: base * 0.01, localContentPct: 1.0 },
    { description: "Support & Maintenance", unit: "Month", qty: 12, unitPrice: base * 0.02, localContentPct: 0.9 },
  ];
}

// ─── PPTX-equivalent (HTML slides bundled in ZIP) ────────────────────────────

export function generateSlidesHTML(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null
): string {
  const primary = brand?.primaryColor ?? "#1E3A8A";
  const accent = brand?.accentColor ?? "#0EA5E9";
  const tenderType = getTenderType(project.category);

  const slides = [
    {
      title: brand?.tagline ?? "Arabclue",
      subtitle: "Technical & Financial Proposal",
      body: `${project.title}<br><span style="opacity:.7">Etimad Ref: ${project.etimadRef ?? "N/A"} · ${tenderType.name}</span>`,
      bg: `linear-gradient(135deg, ${primary}, ${accent})`,
      light: true,
    },
    {
      title: "Executive Summary",
      subtitle: "الملخص التنفيذي",
      body: "Full alignment with <strong>Saudi Vision 2030</strong>. Level C1 compliance with NCA, PDPL, and EA requirements. 10% Local Content preference applied.",
      bg: "#ffffff",
    },
    {
      title: "Execution Methodology",
      subtitle: "5-Pillar Agile + PMI",
      body: EXECUTION_METHODOLOGY.map((m) => `<li><strong>Phase ${m.id}:</strong> ${m.name}</li>`).join(""),
      bg: "#f8fafc",
    },
    {
      title: "Compliance Matrix",
      subtitle: "NCA · PDPL · EA",
      body: COMPLIANCE_FRAMEWORKS.filter((f) => tenderType.complianceScope.includes(f.id))
        .map((f) => `<li><strong>${f.id}:</strong> ${f.controls.length} controls — all COMPLIANT</li>`)
        .join(""),
      bg: "#ffffff",
    },
    {
      title: "Financial Summary",
      subtitle: "الملخص المالي",
      body: `<li>Quick Liquidity Ratio: <strong>1.24</strong> (≥ 1.0) ✓</li>
             <li>Saudization: <strong>42%</strong> (≥ 35%) ✓</li>
             <li>Local Content Preference: <strong>10%</strong> applied</li>
             <li>Budget: ${project.currency} ${(project.budget ?? 0).toLocaleString()}</li>`,
      bg: "#f8fafc",
    },
    {
      title: "Thank You",
      subtitle: brand?.taglineAr ?? "شكراً لكم",
      body: `<em>Generated by Arabclue · PDPL Compliant · KSA Data Residency</em>`,
      bg: `linear-gradient(135deg, ${primary}, ${accent})`,
      light: true,
    },
  ];

  const slidesHtml = slides
    .map(
      (s) => `
    <section class="slide" style="background:${s.bg};color:${s.light ? "#fff" : "#0f172a"}">
      <div class="slide-inner">
        <div class="slide-title">${s.title}</div>
        <div class="slide-subtitle">${s.subtitle}</div>
        <div class="slide-body">${s.body}</div>
      </div>
    </section>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>${project.title} — Slides</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: 'Segoe UI', 'IBM Plex Sans Arabic', sans-serif; background:#1e293b; }
  .slide {
    width:1280px; height:720px; margin:20px auto; border-radius:16px;
    display:flex; align-items:center; justify-content:center;
    box-shadow:0 20px 60px rgba(0,0,0,.4); overflow:hidden;
  }
  .slide-inner { width:80%; }
  .slide-title { font-size:48px; font-weight:800; margin-bottom:12px; }
  .slide-subtitle { font-size:22px; opacity:.8; margin-bottom:28px; font-weight:500; }
  .slide-body { font-size:20px; line-height:1.8; }
  .slide-body li { margin:8px 0; list-style:none; }
  @media print { body { background:#fff; } .slide { box-shadow:none; page-break-after:always; } }
</style></head>
<body>${slidesHtml}
</body></html>`;
}

// ─── ZIP packaging ───────────────────────────────────────────────────────────

export async function generateBidPackageZIP(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null
): Promise<Buffer> {
  const zip = new JSZip();
  const tenderType = getTenderType(project.category);

  // Technical Proposal (printable HTML / PDF)
  const pdf = await generateProposalPDF(proposal, project, brand);
  zip.file("Technical_Proposal.html", pdf);

  // Slides (HTML, printable)
  const slides = generateSlidesHTML(proposal, project, brand);
  zip.file("Technical_Proposal_Slides.html", slides);

  // Compliance Matrix XLSX
  const matrix = await generateComplianceMatrixXLSX(project, brand);
  zip.file("Compliance_Matrix.xlsx", matrix);

  // Financial BoQ XLSX
  const boq = await generateBoQXLSX(project, brand);
  zip.file("Financial_BoQ.xlsx", boq);

  // Raw markdown
  zip.file("Proposal_Content.md", proposal.contentMd ?? "");

  // README
  const readme = `Arabclue Bid Package
====================
Project: ${project.title}
Etimad Ref: ${project.etimadRef ?? "N/A"}
Tender Type: ${tenderType.name} / ${tenderType.nameAr}
Budget: ${project.currency} ${(project.budget ?? 0).toLocaleString()}
Generated: ${new Date().toISOString()}
Compliance Score: ${proposal.complianceScore ?? 100}%

Contents:
1. Technical_Proposal.html        — Full technical proposal (printable / Save as PDF)
2. Technical_Proposal_Slides.html — Executive presentation (printable)
3. Compliance_Matrix.xlsx         — Regulatory compliance matrix
4. Financial_BoQ.xlsx             — Bill of Quantities (Etimad format)
5. Proposal_Content.md            — Raw markdown source

PDPL Compliant · KSA Data Residency · Vision 2030 Aligned
Generated by Arabclue
`;
  zip.file("README.txt", readme);

  const buf = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 9 } });
  return Buffer.from(buf);
}
