import ExcelJS from "exceljs";
import JSZip from "jszip";
import { COMPLIANCE_FRAMEWORKS, EXECUTION_METHODOLOGY, getTenderType } from "./constants";
import type { GeneratedProposal, TenderProject, BrandProfile } from "@prisma/client";
import { LOCAL_CONTENT_PRICE_PREFERENCE } from "./procurement-rules";
import { escapeHtml, markdownToHtml } from "./markdown";

export type PdfLocale = "ar" | "en";

function resolveLocale(proposal: GeneratedProposal, override?: PdfLocale): PdfLocale {
  if (override === "ar" || override === "en") return override;
  const loc = (proposal as { locale?: string }).locale;
  return loc === "en" ? "en" : "ar";
}

function buildProposalHTML(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null,
  opts?: { forPrint?: boolean; locale?: PdfLocale }
): string {
  const primary = brand?.primaryColor ?? "#1E3A8A";
  const accent = brand?.accentColor ?? "#0EA5E9";
  const tenderType = getTenderType(project.category);
  const forPrint = opts?.forPrint ?? true;
  const locale = resolveLocale(proposal, opts?.locale);
  const rtl = locale === "ar";
  const bodyHtml = markdownToHtml(proposal.contentMd ?? "", {
    headingColor: primary,
    accentColor: accent,
  });

  const labels =
    locale === "ar"
      ? {
          subtitle: "العطاء الفني والمالي",
          project: "عنوان المشروع",
          type: "نوع المناقصة",
          budget: "الميزانية",
          evaluation: "التقييم",
          sla: "غرامة التأخير",
          generated: "تاريخ الإنشاء",
          version: "الإصدار",
          print: "حفظ كـ PDF",
          footer: "أُنشئ بواسطة أراب كلاو · متوافق مع PDPL · إقامة البيانات في المملكة · رؤية 2030",
          techFin: `فني ${tenderType.evaluationSplit.technical}% / مالي ${tenderType.evaluationSplit.financial}%`,
          slaVal: `${tenderType.slaPerWeek}% أسبوعياً (حد أقصى ${tenderType.slaMaxPenalty}%)`,
        }
      : {
          subtitle: "Technical & Financial Proposal",
          project: "Project Title",
          type: "Tender Type",
          budget: "Budget",
          evaluation: "Evaluation",
          sla: "SLA Penalty",
          generated: "Generated",
          version: "Version",
          print: "Save as PDF",
          footer: "Generated by Arabclue · PDPL Compliant · KSA Data Residency · Vision 2030 Aligned",
          techFin: `Technical ${tenderType.evaluationSplit.technical}% / Financial ${tenderType.evaluationSplit.financial}%`,
          slaVal: `${tenderType.slaPerWeek}%/week (max ${tenderType.slaMaxPenalty}%)`,
        };

  const logoBlock = brand?.logoUrl
    ? `<img src="${escapeHtml(brand.logoUrl)}" alt="logo" style="height:56px;max-width:180px;object-fit:contain;margin-bottom:16px;background:rgba(255,255,255,.12);padding:6px 10px;border-radius:8px" />`
    : "";

  const titleDisplay =
    locale === "ar"
      ? escapeHtml(project.titleAr || project.title)
      : escapeHtml(project.title);

  return `<!DOCTYPE html>
<html lang="${locale}" dir="${rtl ? "rtl" : "ltr"}"><head><meta charset="utf-8">
<title>${titleDisplay} — ${labels.subtitle}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  @page { size: A4; margin: 16mm; }
  * { box-sizing: border-box; }
  body {
    font-family: 'IBM Plex Sans Arabic', 'IBM Plex Sans', 'Segoe UI', Arial, sans-serif;
    color: #0f172a; margin: 0; line-height: 1.7; font-size: 12px; padding: 10px;
    direction: ${rtl ? "rtl" : "ltr"};
  }
  .cover {
    background: linear-gradient(135deg, ${primary}, ${accent});
    color: white; padding: 40px 32px; border-radius: 12px; margin-bottom: 22px;
  }
  .cover h1 { font-size: 26px; margin: 0 0 8px; color: white; font-weight: 700; }
  .cover .subtitle { font-size: 15px; opacity: 0.92; }
  .cover .ref { font-size: 11px; opacity: 0.85; margin-top: 14px; font-family: ui-monospace, monospace; }
  .meta { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; margin-bottom: 20px; }
  .meta div { display: flex; justify-content: space-between; gap: 12px; padding: 5px 0; border-bottom: 1px dashed #e2e8f0; }
  .meta div:last-child { border: none; }
  .meta .label { font-weight: 600; color: ${primary}; white-space: nowrap; }
  .content { max-width: 100%; }
  h1, h2, h3, h4 { page-break-after: avoid; }
  table { page-break-inside: avoid; }
  .footer { margin-top: 32px; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 8px; }
  ${forPrint ? "" : `.print-btn { position: fixed; top: 16px; inset-inline-end: 16px; background: ${primary}; color: white; border: none; padding: 10px 18px; border-radius: 8px; cursor: pointer; z-index: 10; font-family: inherit; }`}
</style></head>
<body>
  ${forPrint ? "" : `<button class="print-btn" onclick="window.print()">${labels.print}</button>`}
  <div class="cover">
    ${logoBlock}
    <h1>${escapeHtml(locale === "ar" ? brand?.taglineAr || brand?.tagline || "أراب كلاو" : brand?.tagline || "Arabclue")}</h1>
    <div class="subtitle">${labels.subtitle}</div>
    <div class="ref">Etimad: ${escapeHtml(project.etimadRef ?? "N/A")} · ${escapeHtml(tenderType.name)} / ${escapeHtml(tenderType.nameAr)}</div>
  </div>
  <div class="meta">
    <div><span class="label">${labels.project}</span><span>${titleDisplay}</span></div>
    <div><span class="label">${labels.type}</span><span>${escapeHtml(locale === "ar" ? tenderType.nameAr : tenderType.name)}</span></div>
    <div><span class="label">${labels.budget}</span><span>${escapeHtml(project.currency)} ${(project.budget ?? 0).toLocaleString(locale === "ar" ? "ar-SA" : "en-US")}</span></div>
    <div><span class="label">${labels.evaluation}</span><span>${labels.techFin}</span></div>
    <div><span class="label">${labels.sla}</span><span>${labels.slaVal}</span></div>
    <div><span class="label">${labels.version}</span><span>v${proposal.version ?? 1}</span></div>
    <div><span class="label">${labels.generated}</span><span>${new Date(proposal.generatedAt ?? proposal.updatedAt ?? Date.now()).toLocaleString(locale === "ar" ? "ar-SA" : "en-US")}</span></div>
  </div>
  <div class="content">${bodyHtml}</div>
  <div class="footer">${labels.footer}</div>
</body></html>`;
}

export function generateProposalHTMLPreview(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null,
  locale?: PdfLocale
): Buffer {
  return Buffer.from(
    buildProposalHTML(proposal, project, brand, { forPrint: false, locale }),
    "utf8"
  );
}

/** Binary PDF via Playwright Chromium. Throws if browser cannot launch. */
export async function generateProposalPDF(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null,
  locale?: PdfLocale
): Promise<Buffer> {
  let brandForPdf = brand;
  if (brand?.logoUrl?.startsWith("/")) {
    try {
      const { readStoredFile, fileExists } = await import("./storage");
      const pathMatch = brand.logoUrl.match(/path=([^&]+)/);
      if (pathMatch) {
        const storagePath = decodeURIComponent(pathMatch[1]);
        if (await fileExists(storagePath)) {
          const bytes = await readStoredFile(storagePath);
          const ext = storagePath.split(".").pop()?.toLowerCase() ?? "png";
          const mime =
            ext === "jpg" || ext === "jpeg"
              ? "image/jpeg"
              : ext === "webp"
                ? "image/webp"
                : ext === "svg"
                  ? "image/svg+xml"
                  : "image/png";
          brandForPdf = {
            ...brand,
            logoUrl: `data:${mime};base64,${bytes.toString("base64")}`,
          };
        }
      }
    } catch {
      /* keep relative logo — may not render in PDF */
    }
  }

  const html = buildProposalHTML(proposal, project, brandForPdf, { forPrint: true, locale });
  try {
    const { chromium } = await import("playwright");
    const browser = await chromium.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle", timeout: 60_000 });
      // Allow Google Fonts to load for Arabic typography
      await page.waitForTimeout(400);
      const pdf = await page.pdf({
        format: "A4",
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: `<div style="font-size:8px;width:100%;text-align:center;color:#94a3b8;padding:0 12mm;">Arabclue · ${escapeHtml(project.etimadRef ?? "")}</div>`,
        footerTemplate: `<div style="font-size:8px;width:100%;text-align:center;color:#94a3b8;padding:0 12mm;"><span class="pageNumber"></span> / <span class="totalPages"></span></div>`,
        margin: { top: "16mm", bottom: "18mm", left: "12mm", right: "12mm" },
      });
      return Buffer.from(pdf);
    } finally {
      await browser.close();
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(
      `PDF generation failed (Playwright/Chromium unavailable): ${message}`
    );
  }
}

// ─── XLSX generation (Compliance Matrix & BoQ) ───────────────────────────────

export async function generateComplianceMatrixXLSX(
  project: TenderProject,
  brand: BrandProfile | null,
  checks?: { framework: string; controlId: string; title: string; requirement: string; complianceLevel: string | null; status: string; evidence?: string | null }[]
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Arabclue";
  wb.created = new Date();

  const ws = wb.addWorksheet("Compliance Matrix", {
    views: [{ rightToLeft: false }],
    properties: { defaultRowHeight: 20 },
  });

  ws.mergeCells("A1:G1");
  const titleCell = ws.getCell("A1");
  titleCell.value = `Arabclue Compliance Matrix — ${project.title}`;
  titleCell.font = { size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E3A8A" } };
  titleCell.alignment = { vertical: "middle", horizontal: "center" };
  ws.getRow(1).height = 30;

  const headers = ["Framework", "Control ID", "Title", "Requirement", "Level", "Status", "Evidence"];
  headers.forEach((h, i) => {
    const cell = ws.getCell(2, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };
    cell.alignment = { vertical: "middle", horizontal: "center" };
  });

  const tenderType = getTenderType(project.category);
  let row = 3;

  if (checks && checks.length > 0) {
    for (const c of checks) {
      ws.getCell(row, 1).value = c.framework;
      ws.getCell(row, 2).value = c.controlId;
      ws.getCell(row, 3).value = c.title;
      ws.getCell(row, 4).value = c.requirement;
      ws.getCell(row, 5).value = c.complianceLevel ?? "C1";
      ws.getCell(row, 6).value = c.status;
      ws.getCell(row, 7).value = c.evidence ?? "";
      const color =
        c.status === "COMPLIANT"
          ? "FF059669"
          : c.status === "NON_COMPLIANT" || c.status === "GAP"
            ? "FFDC2626"
            : "FFD97706";
      ws.getCell(row, 6).font = { bold: true, color: { argb: color } };
      row++;
    }
  } else {
    for (const fw of COMPLIANCE_FRAMEWORKS.filter(
      (f) => tenderType.complianceScope.includes(f.id) || f.id === "NORA"
    )) {
      for (const ctrl of fw.controls) {
        ws.getCell(row, 1).value = fw.id;
        ws.getCell(row, 2).value = ctrl.controlId;
        ws.getCell(row, 3).value = ctrl.title;
        ws.getCell(row, 4).value = ctrl.requirement;
        ws.getCell(row, 5).value = ctrl.level;
        ws.getCell(row, 6).value = "PENDING";
        ws.getCell(row, 7).value = "";
        row++;
      }
    }
  }

  ws.columns = [
    { width: 16 },
    { width: 14 },
    { width: 28 },
    { width: 45 },
    { width: 10 },
    { width: 12 },
    { width: 40 },
  ];
  ws.views = [{ state: "frozen", ySplit: 2 }];

  void brand;
  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}

export async function generateBoQXLSX(
  project: TenderProject,
  brand: BrandProfile | null,
  boqItems?: {
    item: string;
    unit: string;
    qty: number;
    unitPrice: number | null;
    total: number | null;
  }[]
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Arabclue";
  wb.created = new Date();
  const ws = wb.addWorksheet("Financial BoQ");

  ws.mergeCells("A1:F1");
  const tc = ws.getCell("A1");
  tc.value = `Financial Bill of Quantities — ${project.title}`;
  tc.font = { size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  tc.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E3A8A" } };
  tc.alignment = { vertical: "middle", horizontal: "center" };
  ws.getRow(1).height = 30;

  const headers = [
    "Item #",
    "Description",
    "Unit",
    "Qty",
    "Unit Price (SAR)",
    "Total (SAR)",
  ];
  headers.forEach((h, i) => {
    const cell = ws.getCell(2, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };
  });

  // Structure-only defaults — never invent prices from budget
  const items =
    boqItems && boqItems.length > 0
      ? boqItems
      : [
          { item: "Mobilization & Project Setup", unit: "LS", qty: 1, unitPrice: null, total: null },
          { item: "Design & Architecture", unit: "LS", qty: 1, unitPrice: null, total: null },
          { item: "Build & Implementation", unit: "LS", qty: 1, unitPrice: null, total: null },
          { item: "UAT, Training & Go-Live", unit: "LS", qty: 1, unitPrice: null, total: null },
          { item: "Support & Warranty (12 months)", unit: "LS", qty: 1, unitPrice: null, total: null },
        ];

  let row = 3;
  let subtotal = 0;
  let hasPrices = false;
  items.forEach((it, idx) => {
    ws.getCell(row, 1).value = idx + 1;
    ws.getCell(row, 2).value = it.item;
    ws.getCell(row, 3).value = it.unit;
    ws.getCell(row, 4).value = it.qty;
    if (it.unitPrice != null) {
      ws.getCell(row, 5).value = it.unitPrice;
      hasPrices = true;
    } else {
      ws.getCell(row, 5).value = "—";
    }
    if (it.total != null) {
      ws.getCell(row, 6).value = it.total;
      subtotal += it.total;
      hasPrices = true;
    } else {
      ws.getCell(row, 6).value = "—";
    }
    row++;
  });

  if (hasPrices && subtotal > 0) {
    const vat = Math.round(subtotal * 0.15 * 100) / 100;
    ws.getCell(row, 2).value = "Subtotal";
    ws.getCell(row, 6).value = subtotal;
    row++;
    ws.getCell(row, 2).value = "VAT 15%";
    ws.getCell(row, 6).value = vat;
    row++;
    ws.getCell(row, 2).value = "Grand Total (SAR)";
    ws.getCell(row, 2).font = { bold: true };
    ws.getCell(row, 6).value = subtotal + vat;
    ws.getCell(row, 6).font = { bold: true };
    row += 2;
  } else {
    row++;
  }
  ws.getCell(row, 2).value =
    "Prices are client-entered only. ArabClue does not suggest or calculate bid prices. Local content preference is an evaluation rule under the Government Tenders and Procurement Law.";

  ws.columns = [
    { width: 10 },
    { width: 40 },
    { width: 8 },
    { width: 8 },
    { width: 16 },
    { width: 14 },
  ];

  void brand;
  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}

// ─── Branded HTML slides (preview) + PPTX binary ─────────────────────────────

export interface SlidesMetrics {
  quickLiquidityRatio?: number | null;
  qlrPasses?: boolean | null;
  saudizationPercent?: number | null;
  saudizationTarget?: number | null;
  complianceScore?: number | null;
  localContentPreference?: number;
}

export function generateSlidesHTML(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null,
  metrics?: SlidesMetrics
): string {
  const primary = brand?.primaryColor ?? "#1E3A8A";
  const accent = brand?.accentColor ?? "#0EA5E9";
  const tenderType = getTenderType(project.category);
  const qlr = metrics?.quickLiquidityRatio;
  const qlrOk = metrics?.qlrPasses;
  const saud = metrics?.saudizationPercent;
  const saudTarget = metrics?.saudizationTarget ?? project.saudizationTarget ?? 35;
  const score = metrics?.complianceScore ?? proposal.complianceScore;
  const lcPref =
    metrics?.localContentPreference ?? LOCAL_CONTENT_PRICE_PREFERENCE * 100;

  const qlrLabel =
    qlr != null
      ? `${qlr.toFixed(2)} (≥ 1.0) ${qlrOk === false ? "✗" : "✓"}`
      : "Not extracted from financial docs";
  const saudLabel =
    saud != null
      ? `${saud}% (≥ ${saudTarget}%) ${saud >= saudTarget ? "✓" : "✗"}`
      : `Target ≥ ${saudTarget}% (not extracted)`;

  const slides = [
    {
      title: brand?.tagline ?? "Arabclue",
      subtitle: "Technical & Financial Proposal",
      body: `${escapeHtml(project.title)}<br><span style="opacity:.7">Etimad Ref: ${escapeHtml(project.etimadRef ?? "N/A")} · ${escapeHtml(tenderType.name)}</span>`,
      bg: `linear-gradient(135deg, ${primary}, ${accent})`,
      light: true,
    },
    {
      title: "Executive Summary",
      subtitle: "الملخص التنفيذي",
      body: `Full alignment with <strong>Saudi Vision 2030</strong>. Compliance score <strong>${score ?? "N/A"}%</strong>. Local Content preference <strong>${lcPref}%</strong> applied.`,
      bg: "#ffffff",
    },
    {
      title: "Execution Methodology",
      subtitle: "5-Pillar Agile + PMI",
      body: EXECUTION_METHODOLOGY.map((m) => `<li><strong>Phase ${m.id}:</strong> ${m.name}</li>`).join(""),
      bg: "#f8fafc",
    },
    {
      title: "Compliance Matrix",
      subtitle: "NCA · PDPL · EA",
      body: COMPLIANCE_FRAMEWORKS.filter((f) => tenderType.complianceScope.includes(f.id))
        .map((f) => `<li><strong>${f.id}:</strong> ${f.controls.length} controls evaluated</li>`)
        .join(""),
      bg: "#ffffff",
    },
    {
      title: "Financial Summary",
      subtitle: "الملخص المالي",
      body: `<li>Quick Liquidity Ratio: <strong>${qlrLabel}</strong></li>
             <li>Saudization: <strong>${saudLabel}</strong></li>
             <li>Local Content Preference: <strong>${lcPref}%</strong> applied</li>
             <li>Budget: ${escapeHtml(project.currency)} ${(project.budget ?? 0).toLocaleString()}</li>`,
      bg: "#f8fafc",
    },
    {
      title: "Thank You",
      subtitle: brand?.taglineAr ?? "شكراً لكم",
      body: `<em>Generated by Arabclue · PDPL Compliant · KSA Data Residency</em>`,
      bg: `linear-gradient(135deg, ${primary}, ${accent})`,
      light: true,
    },
  ];

  const slidesHtml = slides
    .map(
      (s) => `
    <section class="slide" style="background:${s.bg};color:${s.light ? "#fff" : "#0f172a"}">
      <div class="slide-inner">
        <div class="slide-title">${s.title}</div>
        <div class="slide-subtitle">${s.subtitle}</div>
        <div class="slide-body">${s.body}</div>
      </div>
    </section>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>${project.title} — Slides</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: 'Segoe UI', 'IBM Plex Sans Arabic', sans-serif; background:#1e293b; }
  .slide {
    width:1280px; height:720px; margin:20px auto; border-radius:16px;
    display:flex; align-items:center; justify-content:center;
    box-shadow:0 20px 60px rgba(0,0,0,.4); overflow:hidden;
  }
  .slide-inner { width:80%; }
  .slide-title { font-size:48px; font-weight:800; margin-bottom:12px; }
  .slide-subtitle { font-size:22px; opacity:.8; margin-bottom:28px; font-weight:500; }
  .slide-body { font-size:20px; line-height:1.8; }
  .slide-body li { margin:8px 0; list-style:none; }
  @media print { body { background:#fff; } .slide { box-shadow:none; page-break-after:always; } }
</style></head>
<body>${slidesHtml}
</body></html>`;
}

/** Binary PowerPoint (.pptx) for Etimad bid packages. */
export async function generateProposalPPTX(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null,
  metrics?: SlidesMetrics
): Promise<Buffer> {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: "LAYOUT_WIDE", width: 13.333, height: 7.5 });
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Arabclue";
  pptx.title = project.title;
  pptx.subject = "Technical & Financial Proposal — Etimad";

  const primary = (brand?.primaryColor ?? "#1E3A8A").replace("#", "");
  const accent = (brand?.accentColor ?? "#0EA5E9").replace("#", "");
  const tenderType = getTenderType(project.category);
  const qlr = metrics?.quickLiquidityRatio;
  const qlrOk = metrics?.qlrPasses;
  const saud = metrics?.saudizationPercent;
  const saudTarget = metrics?.saudizationTarget ?? project.saudizationTarget ?? 35;
  const score = metrics?.complianceScore ?? proposal.complianceScore ?? 0;
  const lcPref =
    metrics?.localContentPreference ?? LOCAL_CONTENT_PRICE_PREFERENCE * 100;

  const qlrLabel =
    qlr != null
      ? `${qlr.toFixed(2)} (≥ 1.0) ${qlrOk === false ? "FAIL" : "PASS"}`
      : "Not extracted from financial documents";
  const saudLabel =
    saud != null
      ? `${saud}% (≥ ${saudTarget}%) ${saud >= saudTarget ? "PASS" : "FAIL"}`
      : `Target ≥ ${saudTarget}% (not extracted)`;

  {
    const s = pptx.addSlide();
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: "100%",
      fill: { color: primary },
    });
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 6.2,
      w: "100%",
      h: 1.3,
      fill: { color: accent },
    });
    s.addText(brand?.tagline ?? "Arabclue", {
      x: 0.8,
      y: 2.2,
      w: 11.5,
      h: 0.6,
      fontSize: 18,
      color: "FFFFFF",
      fontFace: "Arial",
    });
    s.addText(project.title, {
      x: 0.8,
      y: 2.9,
      w: 11.5,
      h: 1.2,
      fontSize: 32,
      bold: true,
      color: "FFFFFF",
      fontFace: "Arial",
    });
    s.addText(
      `Technical & Financial Proposal · Etimad ${project.etimadRef ?? "N/A"} · ${tenderType.name}`,
      {
        x: 0.8,
        y: 4.3,
        w: 11.5,
        h: 0.5,
        fontSize: 14,
        color: "E2E8F0",
        fontFace: "Arial",
      }
    );
    s.addText(brand?.taglineAr ?? "أراب كلاو · رؤية 2030", {
      x: 0.8,
      y: 6.5,
      w: 11.5,
      h: 0.4,
      fontSize: 14,
      color: "FFFFFF",
      fontFace: "Arial",
    });
  }

  {
    const s = pptx.addSlide();
    s.addText("Executive Summary · الملخص التنفيذي", {
      x: 0.6,
      y: 0.4,
      w: 12,
      h: 0.6,
      fontSize: 26,
      bold: true,
      color: primary,
      fontFace: "Arial",
    });
    s.addText(
      `Alignment with Saudi Vision 2030. Compliance score ${score}%. Local Content price preference ${lcPref}% applied per Government Tenders and Procurement Law (نظام المنافسات والمشتريات الحكومية).\n\nEvaluation split: Technical ${tenderType.evaluationSplit.technical}% / Financial ${tenderType.evaluationSplit.financial}%.\n\nSLA penalty cap: ${tenderType.slaMaxPenalty}% (services/construction rules enforced).`,
      {
        x: 0.6,
        y: 1.4,
        w: 12,
        h: 4.5,
        fontSize: 16,
        color: "0F172A",
        fontFace: "Arial",
      }
    );
  }

  {
    const s = pptx.addSlide();
    s.addText("Execution Methodology · منهجية التنفيذ", {
      x: 0.6,
      y: 0.4,
      w: 12,
      h: 0.6,
      fontSize: 26,
      bold: true,
      color: primary,
      fontFace: "Arial",
    });
    s.addText(
      EXECUTION_METHODOLOGY.map((m) => ({
        text: `Phase ${m.id}: ${m.name} / ${m.nameAr}`,
        options: { bullet: true, breakLine: true as const },
      })),
      {
        x: 0.8,
        y: 1.3,
        w: 11.5,
        h: 5,
        fontSize: 16,
        color: "0F172A",
        fontFace: "Arial",
        paraSpaceAfter: 8,
      }
    );
  }

  {
    const s = pptx.addSlide();
    s.addText("Compliance · الامتثال", {
      x: 0.6,
      y: 0.4,
      w: 12,
      h: 0.6,
      fontSize: 26,
      bold: true,
      color: primary,
      fontFace: "Arial",
    });
    s.addText(
      COMPLIANCE_FRAMEWORKS.filter((f) =>
        tenderType.complianceScope.includes(f.id)
      ).map((f) => ({
        text: `${f.id}: ${f.controls.length} controls (NCA ECC/CCC, PDPL, NORA, Local Content)`,
        options: { bullet: true, breakLine: true as const },
      })),
      {
        x: 0.8,
        y: 1.3,
        w: 11.5,
        h: 5,
        fontSize: 15,
        color: "0F172A",
        fontFace: "Arial",
        paraSpaceAfter: 8,
      }
    );
  }

  {
    const s = pptx.addSlide();
    s.addText("Financial Qualification · التأهيل المالي", {
      x: 0.6,
      y: 0.4,
      w: 12,
      h: 0.6,
      fontSize: 26,
      bold: true,
      color: primary,
      fontFace: "Arial",
    });
    s.addText(
      [
        { text: `Quick Liquidity Ratio: ${qlrLabel}`, options: { bullet: true, breakLine: true as const } },
        { text: `Saudization: ${saudLabel}`, options: { bullet: true, breakLine: true as const } },
        { text: `Local Content preference: ${lcPref}%`, options: { bullet: true, breakLine: true as const } },
        {
          text: `Budget: ${project.currency} ${(project.budget ?? 0).toLocaleString()}`,
          options: { bullet: true, breakLine: true as const },
        },
      ],
      {
        x: 0.8,
        y: 1.4,
        w: 11.5,
        h: 4,
        fontSize: 16,
        color: "0F172A",
        fontFace: "Arial",
        paraSpaceAfter: 10,
      }
    );
  }

  {
    const s = pptx.addSlide();
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: "100%",
      fill: { color: primary },
    });
    s.addText("Thank You · شكراً لكم", {
      x: 0.8,
      y: 2.8,
      w: 11.5,
      h: 0.8,
      fontSize: 36,
      bold: true,
      color: "FFFFFF",
      fontFace: "Arial",
      align: "center",
    });
    s.addText(
      "Generated by Arabclue · PDPL Compliant · KSA Data Residency · Vision 2030",
      {
        x: 0.8,
        y: 4,
        w: 11.5,
        h: 0.5,
        fontSize: 14,
        color: "E2E8F0",
        fontFace: "Arial",
        align: "center",
      }
    );
  }

  const out = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.from(out as ArrayBuffer);
}

// ─── ZIP packaging ───────────────────────────────────────────────────────────

export async function generateBidPackageZIP(
  proposal: GeneratedProposal,
  project: TenderProject,
  brand: BrandProfile | null,
  opts?: {
    checks?: Parameters<typeof generateComplianceMatrixXLSX>[2];
    boqItems?: Parameters<typeof generateBoQXLSX>[2];
    slidesMetrics?: SlidesMetrics;
  }
): Promise<Buffer> {
  const zip = new JSZip();
  const tenderType = getTenderType(project.category);

  const pdf = await generateProposalPDF(proposal, project, brand);
  zip.file("Technical_Proposal.pdf", pdf);

  const pptxBuf = await generateProposalPPTX(
    proposal,
    project,
    brand,
    opts?.slidesMetrics
  );
  zip.file("Technical_Proposal_Slides.pptx", pptxBuf);

  const slides = generateSlidesHTML(proposal, project, brand, opts?.slidesMetrics);
  zip.file("Technical_Proposal_Slides.html", slides);

  const matrix = await generateComplianceMatrixXLSX(project, brand, opts?.checks);
  zip.file("Compliance_Matrix.xlsx", matrix);

  const boq = await generateBoQXLSX(project, brand, opts?.boqItems);
  zip.file("Financial_BoQ.xlsx", boq);

  zip.file("Proposal_Content.md", proposal.contentMd ?? "");

  const readme = `Arabclue Bid Package
====================
Project: ${project.title}
Etimad Ref: ${project.etimadRef ?? "N/A"}
Tender Type: ${tenderType.name} / ${tenderType.nameAr}
Budget: ${project.currency} ${(project.budget ?? 0).toLocaleString()}
Generated: ${new Date().toISOString()}
Compliance Score: ${proposal.complianceScore ?? 100}%

Contents:
1. Technical_Proposal.pdf          — Binary PDF (Playwright)
2. Technical_Proposal_Slides.pptx  — Branded PowerPoint slides
3. Technical_Proposal_Slides.html  — HTML slide preview
4. Compliance_Matrix.xlsx          — Regulatory compliance matrix
5. Financial_BoQ.xlsx              — Bill of Quantities (Etimad format)
6. Proposal_Content.md             — Raw markdown source

PDPL Compliant · KSA Data Residency · Vision 2030 Aligned
Generated by Arabclue
`;
  zip.file("README.txt", readme);

  const buf = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 9 },
  });
  return Buffer.from(buf);
}
