/**
 * Guard tests for HTML escaping on every markdown surface that reaches
 * `dangerouslySetInnerHTML`.
 *
 * Proposal section content is authored by other workspace members, generated by
 * the agent pipeline from uploaded tender documents, and can arrive from
 * marketplace templates. A component that hand-rolls markdown-to-HTML instead
 * of using the shared escaping renderer turns that into stored XSS against a
 * reviewer's authenticated session.
 */
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { escapeHtml, markdownToHtml } from "@/lib/markdown";

const REPO_ROOT = join(import.meta.dir, "..", "..", "..");

const XSS_PAYLOADS = [
  `<img src=x onerror="alert(1)">`,
  `<svg onload=alert(1)>`,
  `<script>alert(1)</script>`,
  `<iframe src="javascript:alert(1)"></iframe>`,
  `<a href="javascript:alert(1)">click</a>`,
  `"><img src=x onerror=alert(1)>`,
  `<body onload=alert(1)>`,
];

describe("markdownToHtml escaping", () => {
  // An attribute name such as `onerror=` may legitimately survive as escaped
  // *text*; what must never survive is an actual tag. Assert on emitted tags.
  const DANGEROUS_TAG = /<\s*\/?\s*(img|svg|script|iframe|body|a|object|embed|form|input|link|style|meta)\b/i;

  test.each(XSS_PAYLOADS)("neutralises %s", (payload) => {
    const html = markdownToHtml(payload);
    expect(html).not.toMatch(DANGEROUS_TAG);
    expect(html).toContain("&lt;");
  });

  test("escapes payloads embedded inside markdown constructs", () => {
    const html = markdownToHtml(
      [
        `# <img src=x onerror=alert(1)>`,
        ``,
        `- <svg onload=alert(1)>`,
        ``,
        `| <script>alert(1)</script> | b |`,
        `| --- | --- |`,
        `| c | d |`,
        ``,
        `> <iframe src=javascript:alert(1)>`,
      ].join("\n")
    );
    expect(html).not.toMatch(DANGEROUS_TAG);
  });

  test("still renders legitimate markdown structure", () => {
    const html = markdownToHtml("# Title\n\nSome **bold** text.\n\n- one\n- two");
    expect(html).toContain("<h1");
    expect(html).toContain("<strong>bold</strong>");
    expect(html).toContain("<li");
  });

  test("escapeHtml covers the characters that break out of a text node", () => {
    expect(escapeHtml(`<>&"`)).toBe("&lt;&gt;&amp;&quot;");
  });

  test("escapes ampersands before angle brackets so entities cannot be reformed", () => {
    // Wrong ordering yields `&lt;` from a literal `&amp;lt;`, re-forming a tag.
    expect(escapeHtml("&lt;img&gt;")).toBe("&amp;lt;img&amp;gt;");
  });
});

describe("brand colours cannot escape the style attribute", () => {
  /**
   * The renderer escapes everything in text position but interpolates its two
   * colour options straight into `style="..."`. A value that closes the quote
   * therefore adds an attribute to every heading and blockquote in the preview
   * pane — and unlike the body markdown, the reader never typed it.
   *
   * `/api/brand` currently rejects anything that is not a six-digit hex, so
   * this is a latent hole rather than a live one. It is closed here because the
   * renderer is the choke point: it emits the markup, so it is the only place
   * that stays correct when a second writer of those columns appears.
   */
  const BREAKOUT = `#fff" onmouseover="alert(1)`;

  test("a heading colour that closes the quote cannot add an attribute", () => {
    const html = markdownToHtml("# Title", { headingColor: BREAKOUT });
    expect(html).not.toContain("onmouseover");
  });

  test("an accent colour that closes the quote cannot add an attribute", () => {
    const html = markdownToHtml("> quoted", { accentColor: BREAKOUT });
    expect(html).not.toContain("onmouseover");
  });

  test("a colour option cannot inject a tag either", () => {
    const html = markdownToHtml("## Sub", {
      headingColor: `#fff"><script>alert(1)</script><h2 x="`,
    });
    expect(html).not.toMatch(/<\s*script/i);
  });

  test("legitimate brand colours still reach the markup", () => {
    const html = markdownToHtml("# Title\n\n> quoted", {
      headingColor: "#a1b2c3",
      accentColor: "#112233",
    });
    expect(html).toContain("#A1B2C3");
    expect(html).toContain("#112233");
  });
});

describe("no component hand-rolls a markdown renderer", () => {
  const COMPONENT_FILES = [
    "src/components/dashboard/proposal-builder-preview.tsx",
    "src/components/dashboard/markdown-studio-editor-inner.tsx",
  ];

  test.each(COMPONENT_FILES)(
    "%s builds preview HTML via the shared escaping renderer",
    (relativePath) => {
      const source = readFileSync(join(REPO_ROOT, relativePath), "utf8");
      expect(source).toContain("markdownToHtml");
      // The regression was a local `.replace(/^### .../)` chain feeding
      // dangerouslySetInnerHTML without escaping first.
      expect(source).not.toMatch(/replace\(\s*\/\^#{1,6}\s/);
    }
  );
});
